version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install
            npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependenvcies
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - restore_cache:
          key: v1-dependenvcies
      - run : 
          name: Test front-end
          command: |
            npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
           - build